---
- hosts: nios
  connection: local
  tasks: 
    - name: fetch all networkview objects
      set_fact: 
        networkviews: "{{ lookup('nios', 'networkview', provider=nios_provider) }}"

    - name: check the networkviews
      debug:
        var: networkviews
